# Generated by Django 5.2.4 on 2026-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('summary_en', models.TextField()),
                ('summary_ar', models.TextField()),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField()),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('training', 'Training'), ('partnership', 'Partnership'), ('impact', 'Impact'), ('event', 'Event'), ('media', 'Media')], default='announcement', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
