# Generated by Django 5.2.4 on 2026-06-16 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
